allowBuilds:
  better-sqlite3: true
  canvas: true
  is-hidden-file: true
  libxmljs: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@rollup/rollup-android-arm-eabi@4.63.0'
  - '@rollup/rollup-android-arm64@4.63.0'
  - '@rollup/rollup-darwin-arm64@4.63.0'
  - '@rollup/rollup-darwin-x64@4.63.0'
  - '@rollup/rollup-freebsd-arm64@4.63.0'
  - '@rollup/rollup-freebsd-x64@4.63.0'
  - '@rollup/rollup-linux-arm-gnueabihf@4.63.0'
  - '@rollup/rollup-linux-arm-musleabihf@4.63.0'
  - '@rollup/rollup-linux-arm64-gnu@4.63.0'
  - '@rollup/rollup-linux-arm64-musl@4.63.0'
  - '@rollup/rollup-linux-loong64-gnu@4.63.0'
  - '@rollup/rollup-linux-loong64-musl@4.63.0'
  - '@rollup/rollup-linux-ppc64-gnu@4.63.0'
  - '@rollup/rollup-linux-ppc64-musl@4.63.0'
  - '@rollup/rollup-linux-riscv64-gnu@4.63.0'
  - '@rollup/rollup-linux-riscv64-musl@4.63.0'
  - '@rollup/rollup-linux-s390x-gnu@4.63.0'
  - '@rollup/rollup-linux-x64-gnu@4.63.0'
  - '@rollup/rollup-linux-x64-musl@4.63.0'
  - '@rollup/rollup-openbsd-x64@4.63.0'
  - '@rollup/rollup-openharmony-arm64@4.63.0'
  - '@rollup/rollup-win32-arm64-msvc@4.63.0'
  - '@rollup/rollup-win32-ia32-msvc@4.63.0'
  - '@rollup/rollup-win32-x64-gnu@4.63.0'
  - '@rollup/rollup-win32-x64-msvc@4.63.0'
  - rollup@4.63.0
  - jhtml@0.7.2 || 0.7.3
  - eslint-config-ash-nazg@43.1.0 || 43.1.6
  - eslint-plugin-escompat@3.12.0
  - eslint-plugin-jsdoc@64.3.0 || 64.3.3
  - indexeddbshim@17.4.1 || 17.4.2 || 17.4.3 || 17.5.0 || 17.6.0
  - open@11.0.2
  - powershell-utils@0.2.1
  - websql-configurable@4.0.0
