import {nodeResolve} from '@rollup/plugin-node-resolve';

export default {
  input: 'demo/codemirror.js',
  output: {
    file: 'demo/codemirror.esm.js',
    format: 'esm',
    banner: '// Do not edit this file; it was auto-generated'
  },
  plugins: [
    nodeResolve()
  ]
};
