import {nodeResolve} from '@rollup/plugin-node-resolve';

// Store resolved paths for deduplication
const resolvedCodemirror = new Map();

/**
 * @returns {import('rollup').Plugin}
 */
function dedupeCodemirror () {
  return {
    name: 'dedupe-codemirror',
    /**
     * @param {string} source
     * @param {string|undefined} importer
     * @param {any} options
     * @returns {Promise<string|null>|null}
     */
    resolveId (source, importer, options) {
      if (source === 'codemirror' ||
        source.startsWith('@codemirror/') ||
        source.startsWith('@lezer/')
      ) {
        if (!resolvedCodemirror.has(source)) {
          /* eslint-disable promise/prefer-await-to-then -- sync */
          const promise = this.resolve(
            source, importer, {skipSelf: true, ...options}
          ).then(
            /**
             * @param {any} res
             * @returns {string|null}
             */
            (res) => (res ? res.id : null)
          );
          /* eslint-enable promise/prefer-await-to-then -- sync */
          resolvedCodemirror.set(source, promise);
        }
        return resolvedCodemirror.get(source);
      }
      return null;
    }
  };
}

export default {
  input: 'demo/codemirror.js',
  output: {
    file: 'demo/codemirror.esm.js',
    format: 'esm',
    banner: '// Do not edit this file; it was auto-generated'
  },
  plugins: [
    dedupeCodemirror(),
    nodeResolve()
  ]
};
